version: '3'

services:
  sqlserver_ecommerce:
    container_name: sqlserver_cursoonline
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
    volumes:
      - cursoonline_sqlserver_data:/mcr.microsoft.com/mssql/server

volumes:
  cursoonline_sqlserver_data:
