@HostAddress = http://localhost:5115

POST {{HostAddress}}/Curso
Content-Type: application/json
Accept: */*

{
  "nome": "Meu Curso 1",
  "descricao": "Descrição do curso 1",
  "cargaHoraria": 10,
  "publicoAlvo": "Estudante",
  "valor": 100
}

###
